added layout
js-tasks-ru/htmlcss-20210610_twangste pull request #5
Opened 2021-06-16 20:14 UTC by AStruchenkov

2021-06-16 20:14 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-17 07:57 UTC, GSemikozov requested changes

2021-06-17 07:57 UTC, GSemikozov commented on components/footer.css
> +.footer * {
в БЭМ не стоит использовать универсальные селекторы, кроме того - шрифтовые свойства наследуются, поэтому их достаточно задать 1 раз у блока .footer

2021-06-23 18:18 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-23 19:11 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-23 19:15 UTC, AStruchenkov commented
исправлено

2021-06-23 19:15 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-30 19:55 UTC, AStruchenkov commented on components/footer.css
> +.footer * {
исправил

2021-07-04 09:30 UTC, GSemikozov requested changes

2021-07-04 09:30 UTC, GSemikozov commented on components/footer.css
> +.footer * {
по-прежнему висит

2021-07-04 09:30 UTC, GSemikozov commented on components/footer.css
> +@import '../assets/css/main.css';
подключаем глобально, импортировать в отдельный модуль не надо

2021-07-04 19:16 UTC, AStruchenkov commented on components/footer.css
> +.footer * {
исправил

2021-07-04 19:16 UTC, AStruchenkov commented on components/footer.css
> +@import '../assets/css/main.css';
убрал

2021-07-06 09:47 UTC, GSemikozov approved these changes

2021-07-06 09:47 UTC, merged