skeleton solution
js-tasks-ru/htmlcss-20210610_twangste pull request #7
Opened 2021-06-29 20:14 UTC by AStruchenkov

2021-06-29 20:14 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-30 07:48 UTC, GSemikozov requested changes

2021-06-30 07:48 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.card__container {
то же самое что и в предыдущем ПР-е - все что не относится к блоку уносится в другое место - либо как отдельный блок, либо как глобальный или локальный файл)

2021-06-30 07:48 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +  height: 192px;
по высоте не стоит фиксировать (а вдруг мы захотим еще пару линий добавить)

2021-06-30 07:48 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.header {
это не просто хедер, а элемент скелетона - .skeleton__header
ниже классы тоже надо переименовать по БЭМ

2021-06-30 07:49 UTC, GSemikozov requested changes

2021-06-30 07:49 UTC, GSemikozov commented on assets/css/main.css
> +  width: 75%;
ширину контейнера мы записываем как это определено в макете - max-width: 1110px

2021-06-30 18:18 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-30 18:32 UTC, AStruchenkov commented
исправил замечания

2021-06-30 18:32 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-30 19:38 UTC, AStruchenkov commented on 04-lection2/02-skeleton/skeleton.css
> +.card__container {
перенёс в main.css

2021-06-30 19:38 UTC, AStruchenkov commented on 04-lection2/02-skeleton/skeleton.css
> +  height: 192px;
согласен. исправил

2021-06-30 19:38 UTC, AStruchenkov commented on 04-lection2/02-skeleton/skeleton.css
> +.header {
исправил

2021-06-30 19:39 UTC, AStruchenkov commented on assets/css/main.css
> +  width: 75%;
исправил

2021-06-30 19:45 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-30 19:46 UTC, GSemikozov requested changes

2021-06-30 19:46 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +  padding: 1.5rem 2.5rem 1.5px 1.5rem;
паддинг снизу точно должен быть полтора пикселя?)

2021-06-30 20:01 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-30 20:02 UTC, AStruchenkov commented on 04-lection2/02-skeleton/skeleton.css
> +  padding: 1.5rem 2.5rem 1.5px 1.5rem;
точно не должен :) Исправил

2021-07-06 09:51 UTC, GSemikozov approved these changes

2021-07-06 09:51 UTC, merged