tooltip solution
js-tasks-ru/htmlcss-20210610_twangste pull request #8
Opened 2021-06-30 20:25 UTC by AStruchenkov

2021-06-30 20:26 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-07-01 08:25 UTC, GSemikozov requested changes

2021-07-01 08:25 UTC, GSemikozov commented on assets/css/main.css
> +.card__container {
эта штука - все-таки не элемент карточки, а какой-то самостоятельный блок-враппер. Поэтому, его надо бы как-то соответствующим образом переименовать + если это только для того чтобы врапнуть 1 компонент из дз в хтмл файле из дз - то лучше его туда и перенести))

2021-07-01 20:51 UTC, AStruchenkov commented on assets/css/main.css
> +.card__container {
перенёс в html <style>

2021-07-01 21:06 UTC, GSemikozov approved these changes

2021-07-01 21:06 UTC, merged